### ISSUE TITLE
Get it to work with pm2

### ISSUE THREAD

**Issue by pke** [webfactory/ssh-agent#10]
I struggle to get this to work with `pm2`.

I have create a new SSH key, added it as deploy key in my repo where the action runs. Added it as a secret in the repo too.

Thats the output:

```bash
[PM2] Spawning PM2 daemon with pm2_home=/home/runner/.pm2
[PM2] PM2 Successfully daemonized
--> Deploying to production environment
--> on host xxxx
fatal: HEAD does not point to a branch
  ○ deploying origin/master
  ○ executing pre-deploy-local
  ○ hook pre-deploy
Host key verification failed.
  ○ fetching updates
  ○ full fetch
Host key verification failed.


  fetch failed
```

The action's usage can be reviewed [here](https://github.com/pke/xstate.io/blob/master/.github/workflows/deploy.yml)

And my pm2 [ecosystem file](https://github.com/pke/xstate.io/blob/master/ecosystem.config.js)

**Comment by mpdude** [comment]
I don't know about `pm2`. Does that SSH into another machine? Does `Host key verification failed.` happen there?

**Comment by pke** [comment]
Yes it does SSH into the machine the app should be deployed on. The error happens there

**Comment by mpdude** [comment]
Then you need to find a way how to provision your `known_hosts` key there. I am afraid this action cannot do this for you.

**Comment by pke** [comment]
Ok, thanks for taking the time. I'll try over at pm2 repo to find some answers.

**Comment by pke** [comment]
Ok I figured something out. After disabling strict host checking in my pm2 ecosytem file I got this output:

```bash
[PM2] Spawning PM2 daemon with pm2_home=/home/runner/.pm2
[PM2] PM2 Successfully daemonized
--> Deploying to production environment
--> on host MY.SERVER
fatal: HEAD does not point to a branch
  ○ deploying origin/master
  ○ executing pre-deploy-local
  ○ hook pre-deploy
Warning: Permanently added '[MY.SERVER]:36077,[45.10.26.70]:36077' (ECDSA) to the list of known hosts.
```

So it seems the problem was that host that I wanted deploy to (`MY.SERVER`) was not in the list of `known_hosts` on the GH build instance.
Is that something this action could also take care of? Like it does with adding the private key to the ssh-agent?

**Comment by mpdude** [comment]
My guess would be that there is no benefit of having this in this central action. I've added a note at https://github.com/webfactory/ssh-agent/blob/master/README.md#run-ssh-keyscan-to-add-host-keys-for-additional-hosts.
