### ISSUE TITLE
Public key fingerprints are printed in the logs/output

### ISSUE THREAD

**Issue by TheCleric** [webfactory/ssh-agent#100]
When running this action I see my public key printed in the logs. Granted it is a public key, but this is less than ideal if one does not want to share this information with whoever can view the action result. Ideally this would be configurable with some sort of silent option that suppresses this message.

**Comment by mpdude** [comment]
This has been raised a few times before... Having the key fingerprints in the output helps with debugging, and since it is a public key fingerprint, should not be an issue security-wise?

**Comment by TheCleric** [comment]
Like I said, just having an option to disable it would be nice.

**Comment by mikejoseph-ef** [comment]
appending to this one. it is very crucial to not expose ssh keys public or private to any saved logs, it should be masked, please consider adding this feature.
