### ISSUE TITLE
Unable to read repo after key was added

### ISSUE THREAD

**Issue by FeleConvo** [webfactory/ssh-agent#105]
I'm trying to set up access to a private repository set up as a dependency for a Flutter application.

I followed this: https://github.com/marketplace/actions/webfactory-ssh-agent#usage

and this: https://github.com/marketplace/actions/webfactory-ssh-agent#support-for-github-deploy-keys

The exact command I used to create the key was: 

`ssh-keygen -t ed25519 -a 100 -f id_ed25519_dk -C git@github.com:convo/HighlanderCPaaSAdapterInterface.git`

Yet my current output is:

```
Run webfactory/ssh-agent@v0.5.4
Adding GitHub.com keys to /home/runner/.ssh/known_hosts
Starting ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-7bZnk0tNrFSD/agent.1834
SSH_AGENT_PID=1835
Adding private key(s) to agent
Identity added: (stdin) (git@github.com:convo/HighlanderCPaaSAdapterInterface.git)
Key(s) added:
256 SHA256:J3hmvJ33ojrGpMTZ6XkDo8o76HLDsoyBaowUSqX328c git@github.com:convo/HighlanderCPaaSAdapterInterface.git (ED25519)
Configuring deployment key(s)
Added deploy-key mapping: Use identity '/home/runner/.ssh/key-f1046220a395f9fc1c7756e3e0919722056ccaa2a46bac51ea8178d8ea5f8853' for GitHub repository convo/HighlanderCPaaSAdapterInterface
Comment for (public) key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
```

Followed by:

```
Running "flutter pub get" in flutter_tools...                       5.4s
Running "flutter pub get" in HighlanderSDK...                       4.9s
Running "flutter pub get" in example...                         
Git error. Command: `git clone --mirror git@github.com:convo/HighlanderCerberusAdapter.git /opt/hostedtoolcache/flutter/2.8.1-stable/x64/.pub-cache/git/cache/HighlanderCerberusAdapter-5f89de7adaf6d0c72ce34930f90772f706482734`
stdout: 
stderr: Cloning into bare repository '/opt/hostedtoolcache/flutter/2.8.1-stable/x64/.pub-cache/git/cache/HighlanderCerberusAdapter-5f89de7adaf6d0c72ce34930f90772f706482734'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

I've tried creating keys the same way on my local machine to test them and they seem to work, at least using them to connect to my github account or pulling code locally.

Any thoughts on this?

Is the `Comment for (public) key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.` message where the issue is?

Any help would be appreciated.

:)

**Comment by mpdude** [comment]
> Is the Comment for (public) key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key. message where the issue is?

I think that's a glitch in logging and not relevant here.

I noticed you added the key comment for `convo/HighlanderCPaaSAdapterInterface` but the error occurs when trying to clone `convo/HighlanderCerberusAdapter`.

Is that correct?

**Comment by AshNaz87** [comment]
Hi @mpdude 

Is there a way for this GH Action to work without using a deploy key?

I know there is a section on machine users in the README but the information on it is sparse

**Comment by FeleConvo** [comment]
Hey @mpdude Thanks for your reply.

I re-did everything from zero and found a cross dependency hence why my key wasn't working. Fixed it and it worked.

Feel free to close this :D
