### ISSUE TITLE
Multiple deploy keys does not work during docker image build

### ISSUE THREAD

**Issue by aston-r** [webfactory/ssh-agent#107]
Hi,

I saw a lot of issues regarding this topic, but I have not found the solution for my problem so far:

STR:
- configure deploy keys according to https://github.com/webfactory/ssh-agent#support-for-github-deploy-keys
- try to clone the repositories and everything works as expected and all private repos were successfully cloned
```
- name: Setup SSH Keys and known_hosts
    uses: webfactory/ssh-agent@v0.5.4
    with:
    ssh-private-key: |
        ${{ secrets.REPO1 }}
        ${{ secrets.REPO2 }}
        
- name: Clone repos
    run: |
    git clone git@github.com:Test/repo1.git
    git clone git@github.com:Test/repo2.git          
```

```
Configuring deployment key(s)
Added deploy-key mapping: Use identity '/home/runner/.ssh/key-blabla11' for GitHub repository Test/repo1.git
Added deploy-key mapping: Use identity '/home/runner/.ssh/key-blabla22' for GitHub repository Test/repo2.git          
```

- create docker file and try to clone the same repos during the docker image build
```
- name: Build and push
    id: docker_build
    uses: docker/build-push-action@v2
    with:
    ssh: |
        default=${{ env.SSH_AUTH_SOCK }}
```

here is a part of the docker file:
```
# https://docs.docker.com/develop/develop-images/build_enhancements/#using-ssh-to-access-private-data-in-builds
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
    openssh-client \
    git \
    && apt-get clean

# Download public key for github.com
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
ENV GIT_SSH_COMMAND="ssh -vvv"
RUN --mount=type=ssh echo $(ssh-add -l) && echo $SSH_AUTH_SOCK
RUN --mount=type=ssh git git@github.com:Test/repo1.git
RUN --mount=type=ssh git git@github.com:Test/repo2.git
```

Actual Result:
- only the first repo was successfully cloned during docker image building

according to debug log git clone command uses the first key and git command fails

<details>
9 [builder  4/13] RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
#9 0.721 # github.com:22 SSH-2.0-babeld-00610741
#9 0.887 # github.com:22 SSH-2.0-babeld-00610741
#9 1.049 # github.com:22 SSH-2.0-babeld-00610741
#9 DONE 1.2s

#10 [builder  5/13] RUN --mount=type=ssh echo $(ssh-add -l) && echo $SSH_AUTH_SOCK
#10 0.304 256 SHA256:/blablabla1 git@github.com:Test/repo1.git (ED25519) 256 SHA256:blablabla2 git@github.com:Test/repo2.git (ED25519)
#10 0.304 /run/buildkit/ssh_agent.0
#10 DONE 0.3s

#11 [builder  6/13] RUN --mount=type=ssh git clone git@github.com:Test/repo2.git
#11 0.442 Cloning into 'repo2'...
#11 0.750 OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019
#11 0.751 debug1: Reading configuration data /etc/ssh/ssh_config
#11 0.757 debug1: /etc/ssh/ssh_config line 19: Applying options for *
#11 0.758 debug2: resolving "github.com" port 22
#11 0.760 debug2: ssh_connect_direct
#11 0.760 debug1: Connecting to github.com [140.82.112.4] port 22.
#11 0.796 debug1: Connection established.

#11 0.995 debug1: Will attempt key: git@github.com:Test/repo1.git ED25519 SHA256:/blablabla1 agent
#11 0.995 debug1: Will attempt key: git@github.com:Test/repo2.git ED25519 SHA256:blablabla2 agent

#11 1.075 debug1: Offering public key: git@github.com:Test/repo1.git ED25519 SHA256:/blablabla1 agent
#11 1.075 debug3: send packet: type 50
#11 1.075 debug2: we sent a publickey packet, wait for reply
#11 1.121 debug3: receive packet: type 60
#11 1.121 debug1: Server accepts key: git@github.com:Test/repo1.git ED25519 SHA256:/blablabla1 agent

#11 1.339 Please make sure you have the correct access rights
#11 1.339 and the repository exists.
</details>

for some reason, the magic with selecting the proper ssh key does not work inside of dokcer container, while it works directly on the Github runner server...

**Comment by mpdude** [comment]
Does #78 help?

**Comment by aston-r** [comment]
@mpdude thank you for the reference and quick reply. Unfortunately the solution is hucky, so I will have to think about different approach.
