### ISSUE TITLE
Is it possible to use this lib to run ssh commands on remote servers

### ISSUE THREAD

**Issue by edson-nascimento** [webfactory/ssh-agent#110]
I need to run ssh commands on my remote server, but I didn't want to have to install other libs like `appleboy/ssh-action`...
Would it be possible to run direct ssh commands on remote?

```yml
...
- name: Update remote dependencies
      run: |
        ssh -p ${{ inputs.ssh-port }} ${{ inputs.ssh-user }}@${{ inputs.ssh-host }}
        cd ${{ inputs.ssh-path }}
        npm ci --only=production --ignore-scripts
```

**Comment by mpdude** [comment]
This action sets up `ssh-agent` which then holds the keys for remote authentication.

After that, you should be able robuste `ssh` from a `run` command as well :+1:.
