### ISSUE TITLE
suggestion: support for scoping organization level machine user ssh keys

### ISSUE THREAD

**Issue by leitmedium** [webfactory/ssh-agent#111]
Hey,

it is currently supported to use comments for scoping ssh keys to specific repositories which works well with deployment keys that are bound to one repository. If you follow [GitHub suggestion and make use of machine users and ssh keys](https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users) for organization wide access to repositories you currently cannot scope them to a pattern like `git@github.com/organization/ `. This would however allow to juggle with different types of ssh keys. This applies to owner based matching, too, of course.

If I understand the code right, the easiest solution might be to just allow

```
const parts = key.match(/\bgithub\.com[:/]([_.a-z0-9-]+\/)/i);
```

But I might miss a part of replacement logic here.

Best,

Caspar.

**Comment by mpdude** [comment]
There are duplicate reports for this. I've created #128 to focus the discussion in one issue.
