### ISSUE TITLE
Running it to call other servers than GitHub

### ISSUE THREAD

**Issue by ErwanAugmenteed** [webfactory/ssh-agent#115]
Is it possible to use this to call another server URL? Once our build has been completed we would like to call a server URL to deploy the build. We use OSX has the platform to run the our Runner (this could also be an issue).

**Comment by mpdude** [comment]
This action only sets up the "SSH Agent", a helper program that can hold your SSH keys.

Various commands running over SSH can then make use of these keys. To run commands over SSH, specifically, you could try native `ssh` commands via `run:`, or look for a dedicated action.
