### ISSUE TITLE
The number of ssh-private-key arguments and repo-mappings must match.

### ISSUE THREAD

**Issue by yermukhanbet** [webfactory/ssh-agent#118]
I was trying to install multiple ssh keys to my virtual machine, by researching through existing issue, I found this solution: https://github.com/webfactory/ssh-agent/issues/30#issuecomment-677782910

Which seemed to work perfectly. It works fine on my main repository. However, when I tried to use it on my spm for CI, with following code:
```
- name: Install SSH keys for private repos
      uses: shaunco/ssh-agent@git-repo-mapping
      with:
          ssh-private-key: |
                ${{ secrets.SSH_KEY_REPO1 }}
                ${{ secrets.SSH_KEY_REPO2 }}
          repo-mappings: |
                github.com/organization/repo1
                github.com/organization/repo2
```

it shows this error message:

Error: The number of ssh-private-key arguments and repo-mappings must match.

**Comment by mpdude** [comment]
That syntax was a suggestion, but we decided not go that way and ended up using key comments.

Please see if https://github.com/webfactory/ssh-agent#support-for-github-deploy-keys helps.
