### ISSUE TITLE
Fail to build image with yarn install calling other repo

### ISSUE THREAD

**Issue by boinkbr** [webfactory/ssh-agent#12]
Hi, 

I'm trying to build my docker image (it runs like a charm locally). Locally, i pass docker build args with my private and public key (this key is on the second repo). When yarn install calls the private repo, i get an "not authorized".

My config:

name: Docker Image CI (posts@v1)

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.1.1
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build the Docker image
      run: docker build --build-arg ssh_prv_key="$(cat key)" --build-arg ssh_pub_key="$(cat key.pub)" . --file Dockerfile --tag mydockerimage/image:$(date +%s)

This action above fails.

This action below, fails too.

  - name: Build the Docker image
      run: docker build  . --file Dockerfile --tag mydockerimage/image:$(date +%s)

What i did wrong?

Thanks

Fabio

**Comment by mpdude** [comment]
The `key` file that you seem to have present locally does not exist on the worker node. The key is available in the `ssh-agent` (in-memory) only.

**Comment by mpdude** [comment]
I've added a note for this at https://github.com/webfactory/ssh-agent/blob/master/README.md#provide-the-ssh-key-as-a-file.
