### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by tombh** [webfactory/ssh-agent#121]
I've just migrated my old Travis CI config for [browsh-org/browsh](https://github.com/browsh-org/browsh. And I was dismayed by 2 things, 1. that Github Actions still can't restrict PATs to specific repos and 2. that https://github.com/goreleaser/goreleaser doesn't support SSH_DEPLO_KEYS

Lots of googling and experimenting and your action saved the day in a straightforward and well-documented way. Thank you so much 💚

**Comment by mpdude** [comment]
Thank you @tombh for your kind words!
