### ISSUE TITLE
Warning running on macOS with arm64 (M1) chip

### ISSUE THREAD

**Issue by cjwhitsitt** [webfactory/ssh-agent#127]
I'm running on a self-hosted runner with macOS and an arm64 chip. Doing so produces the following output at the beginning of this action's step.

```
Run webfactory/ssh-agent@v0.5.4
  with:
    ssh-private-key: ***
The node12 is not supported on macOS ARM64 platform. Use node16 instead.
```

I imagine the same would happen with Github-hosted runner with an M1 chip, but I can't confirm.

**Comment by mpdude** [comment]
Could you fork this repo, modify this line

https://github.com/webfactory/ssh-agent/blob/53715f806b226a77eb4f6df0ed1c4ebf5398c10a/action.yml#L10

… specify your fork/branch in your workflow definition and report back if it solves the problem?

**Comment by DilumAluthge** [comment]
It looks like the latest release (0.7.0) now uses `node16`. Does that resolve this issue?

**Comment by cjwhitsitt** [comment]
I've left the organization with the repo that had this issue, so I'm not able to verify anymore

**Comment by mpdude** [comment]
Closing for now. Feel free to re-open if the problem resurfaces.
