### ISSUE TITLE
Upgrade to node version 16

### ISSUE THREAD

**Issue by shawnthye-guru** [webfactory/ssh-agent#131]
https://github.com/webfactory/ssh-agent/blob/26e485b72da53538f103f191ddd325d2f2ef3771/action.yml#L10

see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by bigearsenal** [comment]
Same problem here!

**Comment by sebastiankugler** [comment]
@shawnthye-guru @Leee-xx @dghubble @bigearsenal as we're using ssh-agent ourselves, we will certainly upgrade it to node 16 in time. Of course, PRs are very welcome!

**Comment by bigearsenal** [comment]
https://github.com/webfactory/ssh-agent/pull/132
Please check pr

**Comment by sebastiankugler** [comment]
@bigearsenal Thanks a lot! We will need some time until #132 will be merged as the maintainer of this action is currently on vacation, but I'm sure it won't take months.

**Comment by mpdude** [comment]
Fixed in #132.
