### ISSUE TITLE
Docker SSH Forward not working

### ISSUE THREAD

**Issue by doctenahasib** [webfactory/ssh-agent#141]
runs-on: ubuntu-22.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.private-key }}
      - name: Build docker image
         run: docker compose build --ssh default

Hello I try to forward the SSH Key (multiple deploy keys ${{ secrets.private-key }}) to my `docker compose build` command where inside it does a PHP composer install and fetches private github repositories but without success. It says:
> Cloning into bare repository '/root/.cache/composer/vcs/git-github.com-.....                                      
>     ERROR: Repository not found.                                                 
>     fatal: Could not read from remote repository.                                
>     Please make sure you have the correct access rights                          
>     and the repository exists.    

Does anyone face the same issue ? I tried from version 0.5.4 and up.
Btw it works locally on my mac.

**Comment by FSMaxB** [comment]
I had to enable buildkit with the `DOCKER_BUILDKIT=1` environment variable. That was for pure docker without `docker-compose` though, so not sure if it applies.

**Comment by doctenahasib** [comment]
Does not work either with: `DOCKER_BUILDKIT=1 docker build --ssh default .` I get the same error.

**Comment by mpdude** [comment]
Are you trying to use GitHub Deploy Keys during the Docker build process?

If so, does https://github.com/webfactory/ssh-agent/issues/78 or the recently merged https://github.com/webfactory/ssh-agent/pull/133 help?

If yes, any suggestions what should be added to the README?

**Comment by doctenahasib** [comment]
@mpdude Yes I use Github Deploy Keys but the version 0.7.0 did not fix the problem on my side.

**Comment by d3li0n** [comment]
Not sure if it might help, but does your Dockerfile has these lines?

```Dockerfile
RUN mkdir ~/.ssh
RUN ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh <command to install dependencies>
```

**Comment by doctenahasib** [comment]
@mpdude This is how I mount the ssh into the docker build process and this is working fine on my local machine using mac os 12.6 but not in the CI using multiple deploy keys. When running composer install outside the docker container so basically in the CI than it also works but that's not what I want.

@d3li0n Yes I have it in my Dockerfile which btw is being used as the base image.

```
ONBUILD RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
ONBUILD RUN --mount=type=ssh composer install
```

**Comment by mpdude** [comment]
you will need to copy SSH and Git config files into the build stage to make deployment key mappings work. Please see the README.

However I just notice that the section mentions a specific Docker build action, which you don't use. The problem/solution probably is the same.

**Comment by mpdude** [comment]
@j-riebe Since you wrote #133 and have a good understanding of the problem:

Do you think we could write the README section in a more general way (i.e. for Docker, not a specific action supporting it)?

**Comment by mpdude** [comment]
As a side note, personally I'd avoid using `ssh-keyscan` regularly, especially in automated builds. It blindly accepts whatever keys it is being presented at that moment, defeating the whole purpose of key-based host authentication.

Grab and verify the GH host keys once from their website/blog, and directly put it into your Dockerfile. The keys hardly ever change.

**Comment by doctenahasib** [comment]
@mpdude @j-riebe What about dev environment. Since I am using the same Dockerfile for dev, ci and production servers, this forces me to create an empty `root-config` folder in the repository right ? Because otherwise when running docker in my local machine it would simply break as the Dockerfile has the `COPY` instruction. This works maybe fine for the CI but not for the other environments. Is there a way to avoid this `root-config` folder ?

**Comment by j-riebe** [comment]
Hey @doctenahasib, 

I'd recommend using different Dockerfiles for your dev environment and the production build/ci process (à la "do one thing and do it well"). 

Your dev setup would most likely contain additional dev dependencies anyway that need to be handled separately. So you most likely end up building conditional statements into your Dockerfile or just use separate ones.

**Comment by j-riebe** [comment]
As your error description is not pretty verbose, could you try to turn off host key validation during the actual install?

```Dockerfile
RUN --mount=type=ssh GIT_SSH_COMMAND="ssh -v -o StrictHostKeyChecking=no" <INSTALL COMMAND>
```
Just to make sure, that at least the keys are and settings are configured correctly. 
I remember, that our build tool had some issues with the tweaked hostnames (although this should theoretically use the modified `.known_hosts` created by the ssh-agent action).

Be aware that using this setting in production also has good chances of "defeating the whole purpose of key-based host authentication".

**Comment by j-riebe** [comment]
@doctenahasib Those two lines 
```
#9 1.714 debug1: Offering public key: https://github.com/*** ED25519 SHA256:*** agent
#9 1.714 debug1: Server accepts key: https://github.com/*** ED25519 SHA256:*** agent
```
seam to me, as if the wrong key was used. 
I guess the `***` are those parts that you masked, so you'd be able to do the following:

Check if the key that was "accepted" there is in fact the deploy key for the repo (masked too in line 1?).
If thats not the case (which is very likely) your workflow didn't copy the ssh-agent configuration from the runner (error source 1) into the **correct place** inside your container (error source 2).

In general this problem looks exactly like [mentioned in the docs](https://github.com/webfactory/ssh-agent/blob/master/README.md#support-for-github-deploy-keys) - the _first known key_ might not be the right one.

BTW: Did you already try to use the `docker/build-push-action`?

**Comment by j-riebe** [comment]
And is the workflow at the top exactly what you are using or did you also "mask" some (very essential 😉) parts?

If thats the case, you forgot to copy the git and ssh config to your checked out repo. 

```yml
- name: Prepare git and ssh config for build context run: | mkdir root-config cp -r ~/.gitconfig ~/.ssh root-config/
``` 

If you don't do that, it doesn't matter what you do, Docker just won't know the files -> see docs regarding docker-build-push + Deploy keys for details.

**Comment by j-riebe** [comment]
And is the workflow at the top exactly what you are using or did you also "mask" some (very essential 😉) parts?

If thats the case, you forgot to copy the git and ssh config to your checked out repo. 

```yml
- name: Prepare git and ssh config for build context run: | mkdir root-config cp -r ~/.gitconfig ~/.ssh root-config/
``` 

If you don't do that, it doesn't matter what you do, Docker just won't know that the files exist -> see docs regarding docker-build-push + Deploy keys for details.

**Comment by j-riebe** [comment]
#145

**Comment by doctenahasib** [comment]
@j-riebe Thanks for your help. Finally I was able to make it work by doing simply this:

CI workflow file
```yml
- name: Prepare git and ssh config for build context
  run: |
    cp -r ~/.gitconfig ~/.ssh root-config/
    sed 's|/home/runner|/root|g' -i.bak root-config/.ssh/config
```

Dockerfile
```dockerfile
ONBUILD RUN mkdir -p -m 0600 ~/.ssh
ONBUILD COPY root-config /root/
ONBUILD RUN ssh-keyscan github.com >> ~/.ssh/known_hosts
```

I have created an empty `root-config` folder in my repo because in this way it works for both dev and ci environment. So basically it's copying an empty root-config folder on dev because I do not have deploy keys on my local machine but it's 1 ssh key which has access to all the private repositories. (The problem does not exist in dev with one ssh key).

**Comment by mpdude** [comment]
@j-riebe thank you for the extensive support I was not able to provide!

@doctenahasib how could we improve the documentation, what would have helped you?

**Comment by j-riebe** [comment]
@mpdude See PR #145 for an update of the docs

**Comment by doctenahasib** [comment]
@mpdude This applies only to multiple deploy keys as with one ssh key there is no issue. I would go with @j-riebe proposition. IMO only thing missing is specifying on how we should copy the root-config in the Dockerfile.
