### ISSUE TITLE
Configuring known hosts

### ISSUE THREAD

**Issue by alex-jesper** [webfactory/ssh-agent#155]
Hi,

I am using yarn to download a dependency in my package.json defined like:

`"wFundament": "git+ssh://git@bitbucket.alexandra.dk:7999/rkin/wfundament.git#4366d90dc53",`

I have tested it to work from other systems, but using ssh-agent i get:

`Host key verification failed`

As I understand it, its because the host (bitbucket.alexandra.dk:7999) is not a known host. How does ssh-agent support setting a known host?

Thanks,
Jesper

**Comment by alex-jesper** [comment]
I solved it by adding another step:

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.VC_LAB_LIB_SSH_KEY }}

    - name: Add known host
      run:
        echo ${{ secrets.ALEXANDRA_BITBUCKET_SERVER_HOST }} >> /home/alex-admin/.ssh/known_hosts

My main concern with that is the hard coded path to the `known_hosts` file. How would I determine the path more dynamically?

Thnaks,
Jesper

**Comment by mpdude** [comment]
This is out of scope for what this action was designed for. Using second step in your workflow is the right way to solve it.
