### ISSUE TITLE
Trouble with multiple SSH keys

### ISSUE THREAD

**Issue by TrevorGibson-SR** [webfactory/ssh-agent#156]
Hi there,

I'm currently having trouble with a GitHub Actions workflow where I want to clone multiple private repositories (either hosted in Github or BitBucket). The main issue I'm facing is that I can't successfully clone more than one private GitHub repository. When running the action, the second repo always fails with error:

```
fatal: Could not read from remote repository.
  
Please make sure you have the correct access rights
and the repository exists.
```

The repository that's able to be successfully cloned corresponds to the first SSH key listed in my action .yml file... if I switch the order of the keys, the successfully cloned repo changes as well.

I've made a more detailed issue on a different, related repo, but I was hoping some additional eyes here might be able to help. Here's a link to the full issue:

https://github.com/ros-industrial/industrial_ci/issues/807

Thanks in advance

**Comment by mpdude** [comment]
Does this help?

https://github.com/webfactory/ssh-agent#support-for-github-deploy-keys

**Comment by TrevorGibson-SR** [comment]
@mpdude Thanks for the link. I have tried both with and without deploy key mapping but it doesn't seem to make a difference. When attempting to use deploy key mapping, the output from the ssh-agent step indicates that I have deploy keys mapped to the correct repos so I'm assuming that's "working", at least in the ssh-agent action:

```
...
Added deploy-key mapping: Use identity '/home/runner/.ssh/<key1>' for GitHub repository <repo1>
Added deploy-key mapping: Use identity '/home/runner/.ssh/<key2>' for GitHub repository <repo2>
...
```

**Comment by TrevorGibson-SR** [comment]
### Update
(see [original post](https://github.com/ros-industrial/industrial_ci/issues/807) for details about each specific issue)

#### Issue 1
This is resolved by adding non-GitHub servers to the `known_hosts` file. Sample code is provided [in this post](https://github.com/ros-industrial/industrial_ci/issues/807#issuecomment-1402724570) from the original issue report.

#### Issue 2
The root cause is due to the configuration created by webfactory/ssh-agent with the [deploy key mapping](https://github.com/webfactory/ssh-agent#support-for-github-deploy-keys) feature. The custom .gitconfig settings are not copied into the docker automatically, therefore not allowing more than one private GitHub repo to be cloned.

This can be resolved by passing both the `~/.gitconfig` file and `~/.ssh` directory as mapped locations into the docker container. Specifically for ros-industrial/industrial_ci, [use the `DOCKER_RUN_OPTS` parameter](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#pass-custom-variables-to-docker) to specify the locations to map.

A more permanent fix has been [submitted as a PR](https://github.com/ros-industrial/industrial_ci/pull/815) to the ros-industrial repo, to incorporate mapping these locations as part of the standard codebase.
