### ISSUE TITLE
The ssh-private-key argument is empty with reused workflows

### ISSUE THREAD

**Issue by rtrad89** [webfactory/ssh-agent#157]
I have a workflow (let's call it A) that works fine with this action.

When I try to call it from another workflow B, it gives the error:

```
Error: The ssh-private-key argument is empty. Maybe the secret has not been configured, or you are using a wrong secret name in your workflow file.
```

All I did was adding workflow_call in A:
```
on:
  :
  workflow_call:
```

And calling it as a job in the other workflow B:

```
jobs:

  call-build-job:
    uses: ./.github/workflows/A.yml
```

But the secrete seems to be emptied this way.

**Comment by robinlieb** [comment]
You have two options based on the [GitHub documentation](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) of reuse workflows. Easiest solution in your case would be adding the `secrets: inherit` in your workflow B (which is not the reused one). With that property set you can access your secrets in the reused workflow in the same ways as in the other ones like `${{ secrets.SSH_PRIVATE_KEY }}`. Desired yaml should look something like that:
```
jobs:

  call-build-job:
    uses: ./.github/workflows/A.yml
    secrets: inherit
```

**Comment by mpdude** [comment]
@rtrad89 Let us know if that helps.

**Comment by rtrad89** [comment]
Sure thing, planning to test this soon, thank you for the response!

**Comment by rtrad89** [comment]
Confirming that this solves the issue. I can now reuse the workflow with webfactory's ssh-agent action. Apologies for the trivial question to begin with.
