### ISSUE TITLE
 Error when executing git command. ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory     Host key verification failed.  

### ISSUE THREAD

**Issue by uchar** [webfactory/ssh-agent#174]
Recently when I use your plugin with [GameCi ](https://game.ci/docs/github/builder#private-github-repositories)
```
name: Accessing private repos
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - uses: webfactory/ssh-agent@v0.8.0
    with:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  - uses: game-ci/unity-builder@v2
    with:
      sshAgent: ${{ env.SSH_AUTH_SOCK }}
```

I get this error : 
```
Error when executing git command. ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
    Host key verification failed.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
```

I know GitHub recently changed its public key, but even after updating your action I'm still getting errors, How can I fix this?
related to https://github.com/game-ci/unity-builder/issues/525

**Comment by sebastiankugler** [comment]
@uchar maybe the information in https://github.com/webfactory/ssh-agent/pull/171#issuecomment-1482651132 helps?

**Comment by uchar** [comment]
> @uchar maybe the information in [#171 (comment)](https://github.com/webfactory/ssh-agent/pull/171#issuecomment-1482651132) helps?

I'm a little lost here , since game-ci/unity-builder is a docker image, do they have to add it inside their docker image? I can't find a way to do it manually

**Comment by mpdude** [comment]
I haven't used Docker-based build images so far, I don't know... 

The only explanation would be when this action `webfactory/ssh-agent` is run _inside_ the Docker container. Is that the case?

If it is run _outside_ (on the runner), then the `known_hosts` entry should already be present.

**Comment by uchar** [comment]
@mpdude  Yes I think it is running inside the docker 
I fixed the problem by adding the GitHub ssh key to known hosts manually : 
```
- name: "Add GitHub to the SSH known hosts file"
  run: |
    mkdir -p -m 0700 /home/runner/.ssh
    curl --silent https://api.github.com/meta  | jq --raw-output '"github.com "+.ssh_keys[]' >> /home/runner/.ssh/known_hosts
    chmod 600 /home/runner/.ssh/known_hosts
```
