### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by thisguychris** [webfactory/ssh-agent#18]
Hey again, seems like I keep on bumping to your actions 👋🏻

I've tried adding this, and I get a successful message 
```
Starting ssh-agent
Adding private key to agent
Identity added: (stdin)
```
However, when trying to do a clone or submodule init, I get this:
```
Host key verification failed.
fatal: Could not read from remote repository.
```
I've tried cloning the repo using the key, and it works on my machine. I've seen a note in keyscan but I'm not really sure if it's the correct command

I used this to no avail
` ssh-keyscan -t rsa bitbucket.org | ssh-keygen -lf -`

**Comment by thisguychris** [comment]
nevermind, I'm using ssh-keyscan incorrectly.

resolved using it like this:
`ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts`

**Comment by x-yuri** [comment]
@thisguychris It's generally safer to not rely on `ssh-keyscan`. See a workaround [here][b].

[b]: https://github.com/webfactory/ssh-agent/issues/77#issue-871163450
