### ISSUE TITLE
Update to node20

### ISSUE THREAD

**Issue by ivan-gaydamakin** [webfactory/ssh-agent#200]
Please update your script to node20 because:
Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. GitHub plan is to transition all actions to run on Node 20 by Spring 2024. GitHub will actively monitor the migration's progress and gather community feedback before finalizing the transition date. Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.

**Comment by mpdude** [comment]
#201 has been merge
