### ISSUE TITLE
Self-Hosted Agent Problem

### ISSUE THREAD

**Issue by ModdyLP** [webfactory/ssh-agent#35]
On a self-hosted Agent Instance there pop up some error after building once. The second build shows this: 
```
Run webfactory/ssh-agent@v0.2.0
bind: Address already in use
Adding GitHub.com keys to /root/.ssh/known_hosts
unix_listener: cannot bind to path: /tmp/ssh-auth.sock
Starting ssh-agent
##[error]Command failed: ssh-agent -a /tmp/ssh-auth.sock
bind: Address already in use
unix_listener: cannot bind to path: /tmp/ssh-auth.sock
```

I dont know how i can solve it, do you have an idea?
Best Regards

**Comment by mpdude** [comment]
Please try the current version (0.4.0) and report if it fixes this. Also make sure to kill old agent instances already running.

**Comment by ModdyLP** [comment]
It works now, i had messed up the version yesterday. It was to late for doing this :D thanks anyway
