### ISSUE TITLE
Support passphrases

### ISSUE THREAD

**Issue by danfsd** [webfactory/ssh-agent#37]
The motivation for this issue is well related to #36.

In my case, having this action to support passphrases would allow me to use this action prior to running a binary ([Terraform](https://www.terraform.io/)) that will clone additional Github Repositories. Those repositories are private and are in a organization that requires SSH keys to have passphrases as a SAML policy.

If supporting it is really out of scope, could you please shed me some light on workarounds for this scenario?

Thanks in advance and great job!

**Comment by mpdude** [comment]
Maybe in https://www.webfactory.de/blog/use-ssh-key-for-private-repositories-in-github-actions you will find some ideas how the passphrase could be stored as a secret and passed to `ssh-add` when loading the key?

But I am afraid you won’t be able to do this with this action here, you‘d need to resort to plain shell commands in your workflow definition.
