### ISSUE TITLE
The `add-path` command is deprecated and will be disabled on November 16th.

### ISSUE THREAD

**Issue by mvrska** [webfactory/ssh-agent#49]
`Unable to process command '##[set-env name=SSH_AUTH_SOCK;]/tmp/ssh-auth.sock' successfully.`

Error: The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Self explanatory, thanks

**Comment by mpdude** [comment]
Make sure you use the latest version, this has been fixed a while ago.

**Comment by mvrska** [comment]
Yeah didn't notice the new version, sorry about that
