### ISSUE TITLE
Error: spawnSync ssh-agent ENOENT

### ISSUE THREAD

**Issue by gponty** [webfactory/ssh-agent#51]
Hi, any idea why i have this error ?

Adding GitHub.com keys to /github/home/.ssh/known_hosts
Starting ssh-agent
Error: spawnSync ssh-agent ENOENT

Thank you !

**Comment by mpdude** [comment]
Is the `ssh-agent` binary on your `PATH`?

**Comment by gponty** [comment]
Great, that's work !
Thank you for your help and sorry for your wasted time
