### ISSUE TITLE
Unable to find version v0.4.1

### ISSUE THREAD

**Issue by moulik-deepsource** [webfactory/ssh-agent#57]
Hy @mpdude,

I am trying to use `v0.4.1` but it is unable to find by github actions then I tried for the previous version `v0.4.0` but it is not working also because `--set-env:` is being deprecated by github.

**Comment by mpdude** [comment]
That's strange – https://github.com/webfactory/ssh-agent/tags, the v0.4.1 version is clearly there.

Can you share your action configuration and the output of the action run?

**Comment by mpdude** [comment]
Feel free to reopen if the issue persists.
