### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by wouterds** [webfactory/ssh-agent#6]
Not sure if [I'm using it wrong](https://github.com/wouterds/wouterdeschuyter.be/blob/master/.github/workflows/staging.yml) but I don't think so.

[![Screenshot 2019-10-16 at 13 54 27](https://user-images.githubusercontent.com/1210628/66916905-8ef9d900-f01c-11e9-9c13-4bf0772b0236.jpg)](https://github.com/wouterds/wouterdeschuyter.be/runs/262269955)

Also verified that the key added as secret in Github is actually working.

![Screenshot 2019-10-16 at 14 11 00](https://user-images.githubusercontent.com/1210628/66918162-092b5d00-f01f-11e9-977f-921bc00e1bf0.jpg)

Can anyone that's using this action confirm if it's still working?

**Comment by x-yuri** [comment]
@wouterds It's generally safer to not rely on `ssh-keyscan`. See a workaround [here][b].

[b]: https://github.com/webfactory/ssh-agent/issues/77#issue-871163450
