### ISSUE TITLE
Could you add flag or hide by default a data from stdout?

### ISSUE THREAD

**Issue by lolgear** [webfactory/ssh-agent#61]
Run webfactory/ssh-agent@v0.5.0
Adding GitHub.com keys to /Users/runner/.ssh/known_hosts
Starting ssh-agent
Adding private key to agent
Identity added: (stdin) (my@email.com)
Keys added:
256 `SHA256:< SHA >` my@email.com (ED25519)

Could you add an option ( options ) to hide my@email.com in logs?
Also I would like to hide `SHA256:< SHA >`.

**Comment by mpdude** [comment]
The information is printed to ease debugging.

I might be wrong, but the SHA is not a security-relevant information. The email address should be what you put into the key comment field, so you should be able to remove that from the key.
