### ISSUE TITLE
LFS support for multiple repos

### ISSUE THREAD

**Issue by DaHuoKolmostar** [webfactory/ssh-agent#67]
It works fine with multiple repos as [documented](https://github.com/webfactory/ssh-agent#using-multiple-keys). However, if there are repos with LFS, it would fail.

One work around is to disable LFS by setting `GIT_LFS_SKIP_SMUDGE` environment variable to 1.

But there are circumstances where LFS is really needed to obtain large files. Is there plan to support this?

**Comment by mpdude** [comment]
Closing for now since I don’t see what would need to be done.
