### ISSUE TITLE
Leaks private key in build logs

### ISSUE THREAD

**Issue by stabler** [webfactory/ssh-agent#81]
When I build I get the following text in the actions log:

```
Adding private key(s) to agent
Key(s) added:
3072 SHA256:sgR7...Z7qM user@machine.localdomain (RSA)
Configuring deployment key(s)
Comment for key 'ssh-rsa AA...iNk= user@machine.localdomain' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
```

The key was added to ssh-agent and functionality is correct (I'm not using it as a deploy key), but the full text of the private key is leaked in the build logs. Please fix?

**Comment by stabler** [comment]
Oops- my mistake- this is the public key

**Comment by mpdude** [comment]
You’re the second one who raised this.

If you like, open a PR to slightly change wording of the output to make clear it’s the public key fingerprints.
