### ISSUE TITLE
SCP Workflow on Windows

### ISSUE THREAD

**Issue by dokempf** [webfactory/ssh-agent#86]
Thanks for providing this action, I am a very happy user!

I have recently stumbled across an issue on Windows with one of my use cases: I am using the action to set up a private key, which I then use to copy large, non-public files with `scp` from a VM hosted at my institution to the GitHub runner. The workflow works fine on Linux. On Windows, the action itself is successful, but the `scp` operation in a subsequent step fails with `Permission denied (publickey).`.

After reading carefully through https://github.com/webfactory/ssh-agent/pull/63 I was able to actually fix the problem by replacing my plain usage of `scp` on Windows with `c://progra~1//git//usr//bin//scp.exe`. I am happy to have found this fix, but I really do not like it. I would prefer it if this action could modify the environment such that the correct versions of SSH-related executables are picked up. I can imagine this in both an implicit way (like modifying path variables) or an explicit way (like export e.g. an `SCP_BIN` environment variable for the user to use).

Feel free to ignore and close this if you consider it out of scope of the action.

**Comment by mpdude** [comment]
I was trying to focus the action on setting up the SSH Agent, so I am a bit reluctant to do more than strictly necessary. After all, all that needs to be maintained and fixed for various platforms in the long run.

I would, however, very much welcome a PR that adds a short problem explanation and possible workaround to the https://github.com/webfactory/ssh-agent#additional-information-for-particular-tools-or-platforms section of the README. 

Would you want to do that?
