### ISSUE TITLE
Command Failed ssh-add -

### ISSUE THREAD

**Issue by Skillz4Killz** [webfactory/ssh-agent#9]
Followed directions exactly as stated in README but can not get this to work.

Full YAML: https://github.com/Skillz4Killz/gamer-eris/blob/master/.github/workflows/nodejs.yml

This is the error that appears
![image](https://user-images.githubusercontent.com/23035000/69351348-2b7d4f80-0c49-11ea-9b33-17523518e52f.png)

**Comment by AMTourky** [comment]
What went wrong? I'm having the exact same issue!!

**Comment by Skillz4Killz** [comment]
![image](https://user-images.githubusercontent.com/23035000/70388440-be272980-197f-11ea-830f-3f32dc56b4f3.png)

@AMTourky
